version: '3.3'
name: random-image-bot
services:
  pocketbase: 
    build: ../pocketbase/
    environment:
      APP_URL: 'http://bot:3000'
    volumes:
      - 'pocketbase-data:/pb/pb_data'
    ports:
      - 8080:8080
    restart: always

  bot:
    build: ../
    ports:
      - 3000:3000
    env_file:
      - ../.env
    environment:
      PB_HOST: 'http://pocketbase:8080'
    restart: always
    command: 'npm run start'
    depends_on: 
      - pocketbase

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bot
      - pocketbase

volumes:
  pocketbase-data:
